repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0 # Get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
